version: '3'


services:
  app:
    ports:
      - 8080:8080
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: 'app'
    environment:
        - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/books'
        - 'SPRING_DATASOURCE_USERNAME=postgres'
        - 'SPRING_DATASOURCE_PASSWORD=1234'
        - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'
  postgres:
    image: 'postgres:15'
    container_name: 'postgres'
    ports:
      - 5432:5432
    environment:
        - 'POSTGRES_USER=postgres'
        - 'POSTGRES_PASSWORD=1234'
        - 'POSTGRES_DB=books'