create table person(
                       person_id int primary key generated by default as identity,
                       name varchar(50) not null,
                       age int,
                       email varchar not null,
                       password varchar(12) not null,
                       role varchar
                       CHECK (role = 'ROLE_ADMIN' or role = 'ROLE_USER')
);

create table book(
                     book_id int primary key generated by default as identity,
                     title varchar not null,
                     author varchar(50)
);

create table form(
                     form_id int generated by default as identity,
                     reader_id int references person(person_id),
                     book_id int references book(book_id),
                     date_receipt date,
                     date_returned date

);